source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'AWSRNCognitoUserPools' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for mobile
  pod 'AWSCore', '~> 2.5.2'
  pod 'AWSCognitoIdentityProvider', '~> 2.5.2'

  target 'AWSRNCognitoUserPoolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
