# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AWSRNCognitoUserPools' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AWSRNCognitoUserPools
  pod 'AWSCore', '~> 2.5.2'
  pod 'AWSCognitoIdentityProvider', '~> 2.5.2'

end
